// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  /// VAPID key for Firebase Cloud Messaging (Web Push Notifications)
  /// This is a public key used for web push notification subscriptions
  static const String webVapidKey = 'BLubwTQXRJZo5eGNMWcNKFnDijdAkr_IlBILsDUX7OZn3V9_HC4jsbXuy-MST_A5AqPjRYzlfkojhTDiIZjwR4Q';
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJxOGTP2Cvo4Hm_7-iWs9P24Zhxh3g0Qs',
    appId: '1:221528008029:web:fd696489debba24615f4b4',
    messagingSenderId: '221528008029',
    projectId: 'msi-restaurant',
    authDomain: 'msi-restaurant.firebaseapp.com',
    storageBucket: 'msi-restaurant.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDisutNlhEb-r5ccejmJMWgr-ZMdBKlciY',
    appId: '1:221528008029:android:7e25be4cd5c9a95415f4b4',
    messagingSenderId: '221528008029',
    projectId: 'msi-restaurant',
    storageBucket: 'msi-restaurant.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQPWoy-xhwPjc-HRDtD-5ECF6_Z6HWvhI',
    appId: '1:221528008029:ios:839bf357070b974715f4b4',
    messagingSenderId: '221528008029',
    projectId: 'msi-restaurant',
    storageBucket: 'msi-restaurant.firebasestorage.app',
    iosBundleId: 'com.example.digitalMenuOrder',
  );
}
